// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: helloworldv0.proto

package generated

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloRequestv0 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NestedData *NestedData1 `protobuf:"bytes,2,opt,name=nestedData,proto3" json:"nestedData,omitempty"`
}

func (x *HelloRequestv0) Reset() {
	*x = HelloRequestv0{}
	if protoimpl.UnsafeEnabled {
		mi := &file_helloworldv0_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloRequestv0) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequestv0) ProtoMessage() {}

func (x *HelloRequestv0) ProtoReflect() protoreflect.Message {
	mi := &file_helloworldv0_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequestv0.ProtoReflect.Descriptor instead.
func (*HelloRequestv0) Descriptor() ([]byte, []int) {
	return file_helloworldv0_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequestv0) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelloRequestv0) GetNestedData() *NestedData1 {
	if x != nil {
		return x.NestedData
	}
	return nil
}

type NestedData1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Something1 string `protobuf:"bytes,1,opt,name=something1,proto3" json:"something1,omitempty"` // optional string opt1 =2;
}

func (x *NestedData1) Reset() {
	*x = NestedData1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_helloworldv0_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NestedData1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedData1) ProtoMessage() {}

func (x *NestedData1) ProtoReflect() protoreflect.Message {
	mi := &file_helloworldv0_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedData1.ProtoReflect.Descriptor instead.
func (*NestedData1) Descriptor() ([]byte, []int) {
	return file_helloworldv0_proto_rawDescGZIP(), []int{1}
}

func (x *NestedData1) GetSomething1() string {
	if x != nil {
		return x.Something1
	}
	return ""
}

type HelloResponsev0 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *HelloResponsev0) Reset() {
	*x = HelloResponsev0{}
	if protoimpl.UnsafeEnabled {
		mi := &file_helloworldv0_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloResponsev0) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponsev0) ProtoMessage() {}

func (x *HelloResponsev0) ProtoReflect() protoreflect.Message {
	mi := &file_helloworldv0_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponsev0.ProtoReflect.Descriptor instead.
func (*HelloResponsev0) Descriptor() ([]byte, []int) {
	return file_helloworldv0_proto_rawDescGZIP(), []int{2}
}

func (x *HelloResponsev0) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_helloworldv0_proto protoreflect.FileDescriptor

var file_helloworldv0_proto_rawDesc = []byte{
	0x0a, 0x12, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x76, 0x30, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64,
	0x22, 0x5d, 0x0a, 0x0e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x76, 0x30, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x37, 0x0a, 0x0a, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64,
	0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x68, 0x65, 0x6c,
	0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x44, 0x61,
	0x74, 0x61, 0x31, 0x52, 0x0a, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x22,
	0x2d, 0x0a, 0x0b, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x31, 0x12, 0x1e,
	0x0a, 0x0a, 0x73, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x31, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x73, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x31, 0x22, 0x2b,
	0x0a, 0x0f, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x76,
	0x30, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x4e, 0x0a, 0x07, 0x47,
	0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x12, 0x43, 0x0a, 0x08, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c,
	0x6c, 0x6f, 0x12, 0x1a, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x76, 0x30, 0x1a, 0x1b,
	0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x48, 0x65, 0x6c, 0x6c,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x76, 0x30, 0x42, 0x19, 0x5a, 0x17, 0x61,
	0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x30, 0x3b, 0x67, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_helloworldv0_proto_rawDescOnce sync.Once
	file_helloworldv0_proto_rawDescData = file_helloworldv0_proto_rawDesc
)

func file_helloworldv0_proto_rawDescGZIP() []byte {
	file_helloworldv0_proto_rawDescOnce.Do(func() {
		file_helloworldv0_proto_rawDescData = protoimpl.X.CompressGZIP(file_helloworldv0_proto_rawDescData)
	})
	return file_helloworldv0_proto_rawDescData
}

var file_helloworldv0_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_helloworldv0_proto_goTypes = []interface{}{
	(*HelloRequestv0)(nil),  // 0: helloworld.HelloRequestv0
	(*NestedData1)(nil),     // 1: helloworld.NestedData1
	(*HelloResponsev0)(nil), // 2: helloworld.HelloResponsev0
}
var file_helloworldv0_proto_depIdxs = []int32{
	1, // 0: helloworld.HelloRequestv0.nestedData:type_name -> helloworld.NestedData1
	0, // 1: helloworld.Greeter.SayHello:input_type -> helloworld.HelloRequestv0
	2, // 2: helloworld.Greeter.SayHello:output_type -> helloworld.HelloResponsev0
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_helloworldv0_proto_init() }
func file_helloworldv0_proto_init() {
	if File_helloworldv0_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_helloworldv0_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloRequestv0); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_helloworldv0_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NestedData1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_helloworldv0_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloResponsev0); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_helloworldv0_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_helloworldv0_proto_goTypes,
		DependencyIndexes: file_helloworldv0_proto_depIdxs,
		MessageInfos:      file_helloworldv0_proto_msgTypes,
	}.Build()
	File_helloworldv0_proto = out.File
	file_helloworldv0_proto_rawDesc = nil
	file_helloworldv0_proto_goTypes = nil
	file_helloworldv0_proto_depIdxs = nil
}
